### PR TITLE
Str 3477 oxy v5 - should be merged.

### PR DESCRIPTION
**Pull request by Albrecht-S**
This is a test PR and not really meant to be merged.

Created PR.

### CODE REVIEW

**Comment by Albrecht-S** [comment]
OK, this is a test repository, and we can test whatever we want.
So I decided to merge the 'oxy' scheme now.

**Comment by Albrecht-S** [comment]
Merge of PR #8 was successful.

Close #8.

**Comment by Albrecht-S** [comment]
Note: this PR was implicitly closed by mentioning 'Close #8' in the previous comment.
Nice.
BTW: This comment was written after #8 was closed.

**Comment by erco77** [comment]
> Note: this PR was implicitly closed by mentioning 'Close #8' in the previous comment.
> Nice.

I knew you'd like it :D

**Comment by fab672000** [comment]
Testing post PR comment, should we have any constructive comments after the fact that we noticed only after merging.

**Pull request merged**
