### PR TITLE
Fixed crash on possible user error by gracefully writing "<NULL>" whe…

### PR DESCRIPTION
**Pull request by MatthiasWM**
This is an awesome test case for using GitHub in the future. This incredible new feature can be lost, dropped and removed at any point.

### CODE REVIEW

**Comment by MatthiasWM** [comment]
Nice fix, dude. Now go drink a beer on me.

**Comment by MatthiasWM** [comment]
All them pulls and merges wented wells.

**Comment by Albrecht-S** [comment]
Hmm, there are two additional spaces in the commit. Was this intentionally? This is not conforming ot the FLTK CMP.

Note: This is for testing, isn't it?
I don't know how to reopen the PR#1.

**Comment by MatthiasWM** [comment]
OK, since you said that ...-test will just vanish, I did not bother changing my indentation settings. I used the web UI to first revert my changes here, then committed another change in my fork, started a pull request with a conflict, and ended up fixing the conflict in the GitHub web UI. All went as expected.

**Comment by Albrecht-S** [comment]
Well, my "intervention" was nothing but a test. ;-)
Glad you could fix it so easily. :-)

**Pull request merged**
